language: cpp

os:
  - linux
# Add macOS to build matrix directly via the below matrix.include keys:
# - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gdb
    # docbook-based dependencies required by docs/
    - dblatex
    - docbook-xml
    - docbook-xsl
    - texlive
    - xmltex
    - xsltproc

# Documented matrix of osx_image -> macOS and Xcode version available at:
# https://docs.travis-ci.com/user/reference/osx/
# valgrind targets only the most recent Xcode environment on each macOS family
#
# Due to https://github.com/travis-ci/travis-ci/issues/7587 setting multiple
# values for osx_image directly doesn't multiply the Travis-CI build matrix.
matrix:
  include:
    - os: osx
      osx_image: xcode6.4  # macOS 10.10 and Xcode 6.4
    - os: osx
      osx_image: xcode8    # macOS 10.11 and Xcode 8.0
    - os: osx
      osx_image: xcode9.2  # macOS 10.12 and Xcode 9.2
    - os: osx
      osx_image: xcode9.4  # macOS 10.13 and Xcode 9.4

install: # Add dependencies install here
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  # docbook-based dependencies required by docs/
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docbook docbook-xsl; fi

script:
  - ./autogen.sh && ./configure && make && make regtest
  - make dist
